name: PR title check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  title-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title;
            const body  = pr.body || "";

            // Skip if "Make new" box checked
            if (/Make new/i.test(body)) {
              core.info("Make new checked. Skipping title validation.");
              return;
            }

            // Extract form values
            const typeMatch = body.match(/change_type:\s*(\w+)/);
            const coreName  = body.match(/core_name:\s*(\w+)/);
            const exName    = body.match(/ex_name:\s*(\w+)/);
            const descMatch = body.match(/description:\s*(.+)/);

            const type = typeMatch?.[1];
            const name = type === 'ex' ? exName?.[1] : coreName?.[1];
            const description = descMatch?.[1] || '';

            if (!type || !name || !description) {
              core.setFailed("Missing required fields in PR form.");
              return;
            }

            // Compose the expected title
            const expected = `${type}(${name}): ${description}`;
            if (title !== expected) {
              core.setFailed(`Title must exactly match:\n${expected}`);
            }
